<hr />
</div>

<div class="links">
<?php
	include($inc_path . "x_menu.inc");
?>
</div>

<div class="foot">
	<hr />
	<p class="wmo-invite">
		Navštivte oficiální stránky:
		<a href="http://www.mozilla-europe.org/cs/products/firefox/"
			hreflang="cs" lang="en"
			title="Mozilla Europe: Mozilla Firefox">Mozilla Firefox</a>
		&middot;
		<a href="http://www.mozilla-europe.org/cs/"
			hreflang="cs" lang="en">Mozilla Europe</a>
		&middot;
		<a href="http://www.mozilla.org/"
			hreflang="en" lang="en">Mozilla.org</a>
		&middot;
		<a href="http://www.czilla.cz/">CZilla</a>
	</p>
	<p>
		Copyright (c) 2004&ndash;2006 <a href="http://www.czilla.cz/czilla/lide.html">Tým CZilla</a>.
		&nbsp;Hostováno: <a href="http://www.iinfo.cz/">Internet Info</a>
		&nbsp;Vyhledávání: <a href="http://jyxo.cz/">Jyxo</a>
	</p>
	<?php
		if($webstats) {
			?><div class="webstats">
			<script src="http://c1.navrcholu.cz/code?site=75320;t=lg80" type="text/javascript"></script><noscript><div><a
				href="http://navrcholu.cz/"><img src="http://c1.navrcholu.cz/hit?site=75320;t=lg80;ref=;jss=0"
				width="80" height="15" alt="NAVRCHOLU.cz" style="border:none" /></a></div></noscript>
			</div><?php
			}
	?>
</div>
</div>
</body>
</html>
