<?php
	$rootPath = '../../';
	include($rootPath . '../cas/includes-web.inc.php');
	$page->title    = 'Často kladené otázky k Firefoxu';
	$page->headline = array('Často kladené otázky','Na co se nás uživatelé často ptají');

	$page->setKeywords('podpora, otázky, nápověda, pomoc, návod, mozilla, firefox, prohlížeč');
	$page->setDescription('Stránka často kladených otázek ohledně prohlížeče Mozilla Firefox');

	$page->addSideBox('menu','podpora');
	$page->addSideBox('links');
	$page->addSideBox('tips','firefox');

	$page->includeHeader();
	$page->includeFile('tips');
?>

<p>Tento dokument shrnuje často kladené otázky (<abbr title="Frequently Asked Questions">FAQ</abbr>) o prohlížeči Mozilla Firefox.</p>
<a name="contents"></a>
<?php
$faq = new faqTips('ff',1);
$faq->addSection('Všeobecné otázky');
$faq->addQuestion('Co je to Mozilla Firefox&#8482;?','<p>Mozilla Firefox&#8482; je webový prohlížeč s <a href="/podpora/suite/start/open-source.html">otevřeným kódem</a> pro Windows a Linux založený na prohlížeči Mozilla. Je malý, rychlý a snadno použitelný. Ve srovnání se standardní instalací Internet Exploreru nabízí řadu výhod - např. blokování vyskakovacích (pop-up) oken, prohlížení v panelech a uživatelsky přizpůsobitelné lišty. Více informací o tomto programu se dozvíte na <a href="http://www.mozilla.org/projects/firefox/">domovské stránce</a> projektu.</p>');

$faq->addQuestion('Co je to Mozilla?','<p>Mozilla je balík Internetových aplikací s <a href="/podpora/suite/start/open-source.html">otevřeným kódem</a>, navržený s ohledem na dodržování standardů, výkonost a přenositelnost. Více informací o Mozille a mozilla.org se můžete dozvědět na přeložené <a href="/podpora/suite/start/">startovní stránce</a> Mozilly 1.0 nebo přímo na <a href="http://www.mozilla.org/mozorg.html">Mozilla.org</a>.</p>');

$faq->addQuestion('Jaký je rozdíl mezi prohlížečem Mozilla Firefox a Mozillou?','<p>Mozilla je kompletní sada Internetových aplikací, např. webový prohlížeč, poštovní klient, IRC Chat klient a editor webových stránek, DOM Inspector, atd. Mozilla Firefox je samostatný prohlížeč, postavený na prohlížeči z balíku Mozilla - tj tento prohlížeč rovněž využívá renderovací jádro Gecko, jazyk XUL pro popis uživatelského rozhraní, stejně jako většinu kódu komponent XPCOM, které zajišťují základní činnosti prohlížeče. Díky oddělení mohla být řada věci zjednodušena a vylepšena. Tento prohlížeč vás tedy překvapí především svou rychlostí, snadným nastavením lišt a řadou lehce instalovatelných rozšířeních.</p>');

$faq->addQuestion('Kde mohu získat prohlížeč Mozilla Firefox?','<p>Českou verzi prohlížeče Mozilla Firefox naleznete na <a href="/produkty/firefox/stahnout.html">našem serveru</a>. Originální verzi Mozilla Firefox získáte např. z <a href="http://www.mozilla.com/firefox/">Mozilla.com</a>.</p>');

$faq->addQuestion('Jak nainstaluji prohlížeč Mozilla Firefox?','<p>Originální verze prohlížeče Mozilla Firefox je šířena ve formě komprimovaného archivu (zip či tar.gz) a nemusí se instalovat. Pouze stačí komprimovaný soubor rozbalit do vámi vybraného adresáře. Některé lokalizované verze pro OS Windows (včetně české verze!) jsou šířeny ve formě instalačního programu, který vás provede celou instalací. Uživatelé Windows nainstalují prohlížeč Mozilla Firefox spuštěním souboru <tt>firefox.exe</tt>, uživatelé Linuxu pak skriptu <tt>firefox</tt>. Pokud chcete používat klávesové zkratky pro prohlížeč Mozilla Firefox, budete je muset vytvořit ručně.</p><p>Pozn.: Příští verze Mozilla Firefox budou oficiálně šířeny ve formě instalačního programu.</p>');

$faq->addQuestion('Jaký je rozdíl mezi stabilní verzí a nočními verzemi?','<p>Stabilní verze (releases) jsou více odladěné verze prohlížeče Mozilla Firefox. Tyto verze by měli začínající uživatelé preferovat. Noční verze jsou vydávány každou noc a obsahují nejnovější změny, včetně nových vlastností a oprav chyb. Neočekávejte že všechno bude v nočních verzích pracovat správně. Pozn: Neočekávejte, že <i>úplně všechno</i> bude pracovat správně také ve stabilních verzích.</p>');

$faq->addQuestion('Kde naleznu poštovního klienta?','<p>Prohlížeč Mozilla Firefox je jenom webový prohlížeč, nejedná se o kompletní sadu Internetových programů. Vývojáři z Mozilla.org se rovněž soustředí na vývoj samostatného poštovního klienta (zahrnujícího též prohlížeč diskusních skupin), který bude rovněž postavený na poštovním klientu z balíku Mozilla.</p>');

$faq->addQuestion('Jsem uživatel Linuxu, podporuje prohlížeč Mozilla Firefox XFT?','<p>Ano, ale podpora XFT není standardně dostupná. Pro její použití, máte tři možnosti:</p> <ul class="disc"><li>Můžete si vytvořit vlastní verzi prohlížeče přímo ze zdrojových kódů. Pro zapnutí XFT, přidejte "ac_add_options --enable-xft" do vašeho .mozconfig</li><li>Jste-li uživatel Red Hat 8.0, můžete aktualizovat na neoficiální a <i>nepodporované</i> balíčky s podporou XFT z <a href="http://www.sitemason.com/page/eCIDQc">sitemason.com</a></li><li>Můžete si stáhnout balíček Mozilly se zapnutou podporou XFT z <a href="http://ftp.mozilla.org/pub/mozilla/nightly/experimental/xft/">ftp.mozilla.org</a> a nahradit soubor <tt>MozillaFirefox/components/libgfx_gtk.so</tt> ze staženého balíčku.</li></ul>');

$faq->addQuestion('Jak spustím Správce profilů?','<p>Správce profilů vám umožní vytvořit různé profily, každý s vlastními záložkami, předvolbami, atd. Při prvním spuštění se automaticky vytvoří výchozí profil (tzv. default), který prohlížeč Mozilla Firefox používá. Po vytvoření dalšího uživatelského profilu budete vždy při startu prohlížeče dotázáni, který profil si přejete použít.</p><p>Pro spuštění Správce profilů ukončete (kompletně) prohlížeč Mozilla Firefox a spusťte program Mozilla Firefox s přepínačem <tt>-p.</tt> Používáte-li Windows, použijte tyto kroky:</p><ol><li>Vyberte v nabídce <tt>Soubor &gt; Ukončit.</tt></li><li>Vyberte <tt>Start &gt; Spustit...</tt> ze systémové nabídky Windows.</li><li>Zadejte plnou cestu k Mozilla Firefox uzavřenou do uvozovek a přidejte přepínač <tt>-p</tt>, např.:<br /> <tt>"C:\Program Files\Mozilla Firefox\firefox.exe" -p</tt></li></ol><p>Po spuštění "Správce Profilů" v něm můžete přidávat, odstraňovat nebo přejmenovat své profily.</p>');

$faq->addQuestion('Co je Talkback?','<p>Pokud prohlížeč Mozilla Firefox spadne, spustí se program Talkback a požádá vás o odeslání informací odhadujících příčinu pádu prohlížeče. Asa Dotzler z <a href="http://www.mozilla.org/" hreflang="en">mozilla.org</a> napsal pěkné vysvětlení, co je to "Talkback":</p><p>Talkback je program typu klient-server věnovaný fy. Netscape vývojářům z mozilla.org. Vývojáři se před mnoha lety dohodli udělit výjimku a zahrnout tento program do stabilních verzí, přestože to není program s otevřeným kódem, protože poskytuje cenné informace pro odstraňování chyb a hledání problémů se stabilitou. Talkback byl použit při identifikaci a odstraňování tisíců kritických chyb v Mozille za poslední roky a my jsme rádi, že ho může obsahovat i prohlížeč Mozilla Firefox.</p><p>Pokud se chcete naučit Talkback používat, přečtěte si náš článek <a href="/podpora/talkback.html">Talkback - pomocník při pádu Mozilly</a>.</p>');

$faq->addQuestion('Jaký bude další vývoj prohlížeče Mozilla Firefox?','<p>Prohlížeč Mozilla Firefox stane základem pro nový výchozí prohlížeč balíku Mozilla. Současný vše-integrující balík bude totiž nahrazen samostatnými aplikacemi. K tomuto kroku ale nedojde určitě dříve než po vydání verze Mozilla 1.4. a verze Mozilla Firefox 0.7. Vypadá to, že nový výchozí balík Mozilly bude obsahovat prohlížeč Mozilla Firefox (alias Mozilla Prohlížeč) a poštovního klienta Mozilla Thunderbird (alias Mozilla Pošťák) společně se spoustou doplňujících Rozšířeních (např. IRC Chat, DOM Inspector a Venkman). Tyto rozšíření si budete moci libovolně nainstalovat, či odinstalovat. Výhledově si Mozilla bude umět pamatovat, která všechna rozšíření máte nainstalovaná a při instalování nové verze vám je automaticky zaktualizuje.</p>');

$faq->addQuestion('Bude Firefox stále dostupný jako a samostatný prohlížeč i po těchto změnách?','<p>Prohlížeč Mozilla Firefox se určitě bude moci stáhnout i samostatně i po těchto změnách. Plánuje se webový instalátor, který bude znamenat stažení 100KiB a poté vybrání jakékoliv komponenty, kterou chcete. Rovněž by měla být možnost stáhnutí prohlížeče zabaleného v zip archívu.</p>');

$faq->addQuestion('Co se stane se současným balíkem Mozilly?','<p>Jestliže si hodně lidí bude přát pokračování vývoje současného vše-integrujícího balíku, může se tak stát. Avšak vývojáři z Mozilla.org se bude převážně zaměřovat na nové balíčky se samostatnými aplikacemi.</p>');

$faq->addSection('Zásuvné moduly');
$faq->addQuestion('Obsahuje prohlížeč Mozilla Firefox podporu pro zásuvné moduly?','<p>Ano, tato podpora je stejná jako v podpora zásuvných modulů v prohlížeči Mozilla. Pokud máte nainstalovaný prohlížeč Mozilla a chcete používat stejné zásuvné moduly, stačí pokud zkopírujete všechny soubory z adresáře plugins z prohlížeče Mozilla do prohlížeči Mozilla Firefox. Používané zásuvné moduly můžete vidět na stránce about:plugins (do pole s adresou zadejte about:plugins a stiskněte Enter).</p>');

$faq->addQuestion('Je možné nějak sdílet zásuvné moduly?','<p>Ano, stačí pokud vytvoříte adresář pro sdílení zásuvných modulů, vaše moduly do něj nakopírujete a nastavíte systémovou proměnnou <tt>MOZ_PLUGIN_PATH</tt> na cestu k tomuto adresáři. Používáte-li novější Windows, použijte tyto kroky:</p><ol><li>Vytvořte adresář pro sdílení zásuvných modulů - např. <tt>c:\Program Files\Common Files\mozilla.org\Plugins</tt> a nakopírujte do něj vaše moduly.</li><li>Ze systémové nabídky Windows vyberte <tt>Start &gt; Nastavení &gt; Ovládací Panely &gt; Systém.</tt></li><li>Dále zvolte panel Upřesnit, klepněte na Proměnné prostředí a pak na tlačítko Nová.</li><li>Vložte název proměnné MOZ_PLUGIN_PATH a hodnotu c:\Program Files\Common Files\mozilla.org\Plugins</li>
</ol>');

$faq->addQuestion('Jak nainstalovat Flash?','<p>Používáte-li Windows, najdete tento oblíbený zásuvný modul <a href="http://www.macromedia.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&amp;P5_Language=English">zde</a>. Pro uživatele Linuxu, by měl fungovat <a href="http://www.macromedia.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&amp;P2_Platform=Linux&amp;P3_Browser_Version=Netscape4&amp;P5_Language=English">tento zásuvný modul</a>. Stáhněte soubor, ukončete prohlížeč Mozilla Firefox (<tt>Soubor &gt; Ukončit</tt>) a spusťte instalaci. V dialogu instalace klepněte na tlačítko <span class="button">Other browser...</span>. Zde musíte zadat cestu k adresáři zásuvných modulů, který se nachází v adresáři "plugins" v adresáři s nainstalovaným prohlížečem Mozilla Firefox. Vyberte tento adresář a klepněte na tlačítko <span class="button">Select</span>, poté klepněte na tlačítko <span class="button">Install</span>.</p>');

$faq->addQuestion('Jak se instaluje Java?','<p>Pro instalaci Javy pro Windows, klepněte <a href="ftp://ftp.netscape.com/pub/netscape/plugins/java/english/windows/win32/jre140_01i.xpi">zde</a>. Pro Linux, klepněte <a href="ftp://ftp.netscape.com/pub/netscape6/english/6.2.2/unix/linux22/plugins/jre131_02.xpi">zde</a>.</p>');

$faq->addQuestion('Jak nainstalovat další zásuvné moduly?','<p>Pokud vás zajímá, jak nainstalovat i jiné zásuvné moduly, měli byste navštívit stránky <a href="http://plugindoc.mozdev.org/">PluginDoc</a>. Část těchto stránek (zásuvné moduly v Mozille) je i v <a href="/doplnky/zasuvne-moduly/">češtině.</a></p>');

$faq->addSection('Rozšíření');
$faq->addQuestion('Co je to Rozšíření prohlížeče Mozilla Firefox?','<p>Rozšíření je vlastně malý prográmek (přídavný modul), který rozšiřuje funkcionalitu prohlížeče Mozilla Firefox. Může to být v podstatě cokoliv od nového tlačítka na liště po nějakou sofistikovanou věc jako třeba rozšíření mouse gestures. Výhodou tohoto přístupu je, že Mozilla Firefox zůstává stále malým a rychlým prohlížečem. Požadujete-li tady nějakou vlastnost navíc, není nic jednoduššího, než si stáhnout požadované rozšíření.</p>');

$faq->addQuestion('Jak odinstalovat Rozšíření?','<p>To bohužel nejde tak jednoduše jako ho přidat. Příští verze prohlížeče Mozilla Firefox by měla už mít podporu pro jednoduché odinstalování zvoleného Rozšíření, nyní ho můžete pouze zablokovat. Vyberte <tt>Nástroje &gt; Možnosti... &gt; Rozšíření</tt>. Zde zvolte vámi vybrané rozšíření a klepněte na tlačítko Zablokovat Rozšíření. Poznámka: Pro aktivaci zablokovaných Rozšíření je potřeba restartovat prohlížeč.</p>');

$faq->addQuestion('Chtěl bych větší podporu prohlížení v panelech!','<p>Pravděpodobně byste si měli nainstalovat Tabbrowser Extensions, které přidá do prohlížeče takové vychytávky jako je tlačítko Zavřít pro aktuální panel, volba pořadí zavírání panelů, automatická aktualizace panelů, či zotavení po pádu prohlížeče..</p>');

$faq->addQuestion('Co je Mouse Gestures?','<p>Mouse Gestures je pěkná vychytávka obsažená ve výchozí instalaci prohlížeče Opera, která umožňuje jednoduché použití pohybů myši k nadefinování akcí prohlížeče. Například o jednu stránku zpět se můžete přesunout prostřednictvím zmáčknutého levého tlačítka a táhnutím myši doleva. Pro více informací o této vychytávce v prohlížeči Mozilla Firefox se podívejte se na <a href="http://optimoz.mozdev.org/gestures/">domovskou stránku</a> projektu.</p>');

$faq->addSection('Způsob použití');

$faq->addQuestion('Můžu si přizpůsobit lišty prohlížeče?','<p>Ano, toto je jedna z výhod oproti prohlížeči Mozilla. Pokud chcete pouze některé nástrojové lišty schovat, přejděte do nabídky <tt>Zobrazit &gt; Nástrojové lišty</tt> a zvolte, které lišty chcete mít zobrazeny. Pro vlastní nastavení lišt, pak klepněte na tlačítko <tt>Vlastní...</tt> Otevře se vám nové vyskakovací okno, které bude obsahovat dostupné položky (tlačítka, pole, atd.) pro nástrojové lišty. Pokud chcete některou položku přidat, uchyťte ji myší a přetáhněte ji na požadované místo. Pro odstranění položky z nástrojové lišty ji uchyťte myší a přetáhněte zpět na okno s položkami.</p><p>Můžete rovněž přidat další lištu, nebo přetáhnout všechny položky na lištu s nabídkou. (Pozn: Pokud je lišta prázdná měla by se automaticky zrušit.) V současnosti vám prohlížeč ještě nedovolí, abyste mohli přesouvat celé nástrojové lišty - viz <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=172818">chyba 172818.</a></p>');

$faq->addQuestion('Můžu si přizpůsobit ikonku prohlížeče?','<p>Chcete-li si změnit ikonku prohlížeče, postupujte podle návodu uvedeném v dokumentu <a href="tipy-a-triky.html#tips:acf50064ca6951b96a98bdcbbd2c4e4e">Tipy &amp; triky.</a></p>');

$faq->addQuestion('Můžu používat jiný motiv vzhledu?','<p>Samozřejmě ano! Podívejte se na stránku <a href="https://addons.mozilla.org/themes/?application=firefox">Mozilla Update</a>, vyberte si téma, které se vám líbí a nainstalujte si ho.</p>');

$faq->addQuestion('Obsahuje Firefox kontrolu pravopisu?','Ano, na stránce <a href="http://www.czilla.cz/doplnky/kontrola-pravopisu/">kontrola pravopisu</a> najdete podrobnosti o&nbsp;instalaci a&nbsp;přidávání dalších jazykových slovníků.');

$faq->addQuestion('Jaká je klávesová zkratka pro vychytávku XY?','<p>Viz. tabulka <a href="http://www.mozilla.org/support/firefox/keyboard">klávesových zkratek</a> na serveru <a href="http://www.mozilla.org/support/firefox/">Mozilla.org.</a></p>');

$faq->addQuestion('Jak mám převést své staré záložky?','<p>Prohlížeč Mozilla Firefox používá stejný formát (HTML) pro ukládání záložek jako prohlížeč Mozilla. Záložky tak můžete převést pomocí klasického postupu - export záložek z prohlížeče Mozilla (<tt>Správce záložek &gt; Nástroje &gt;Export</tt>) a import do prohlížeče Mozilla Firefox (<tt>Správce záložek &gt; Soubor &gt; Import</tt>) nebo prostým překopírováním souboru bookmarks.html z uživatelského profilu prohlížeče Mozilla do uživatelského profilu prohlížeče Mozilla Firefox. Pokud byste chtěli záložky sdílet, postupujte podle návodu uvedeném v dokumentu <a href="tipy-a-triky.html#tips:cb5811bb663d811e8a3cc38362e50ba5">Tipy &amp; triky.</a></p><p>Prohlížeč Opera používá vlastní formát ADR. Pro převod záložek budete potřebovat nějaký externí program pro jejich správu. Jestliže používáte Windows, můžete své záložky převést pomocí programu <a href="http://homepage.uibk.ac.at/%7Ecsab3666/">BookmarkPriest</a>, používáte-li Linux, zkuste program nazvaný <a href="http://www2.fht-esslingen.de/%7Eclfuit00/sasnt/bk_edit/">bk_edit.</a></p><p>Prohlížeč Internet Explorer používá pro ukládání záložek proprietární formát .url pro Oblíbené položky. Nejjednodušší cestou, jak převést své záložky je export záložek z prohlížeče Internet Explorer (<tt>Soubor &gt;Import a Export</tt>) a import do prohlížeče Mozilla Firefox (<tt>Správce záložek &gt; Soubor &gt; Import</tt>) nebo použít prográmek uvedený výše.</p><p>Prohlížeče Galeon a Konqueror používají pro ukládání záložek formát <a href="http://pyxml.sourceforge.net/topics/xbel/">XBEL.</a> Oba tyto prohlížeče však nabízejí export do souboru ve formátu HTML, který pak můžete v prohlížeči Mozilla Firefox importovat (<tt>Správce záložek &gt; Soubor &gt; Import</tt>). K převodu můžete rovněž použít prográmek uvedený výše.</p>');

$faq->addQuestion('Kde je kontextová nápověda [tooltips] u obrázků?','<p>Mnoho stránek používá atribut <tt>alt</tt> jazyka HTML pro zobrazování kontextové nápovědy u obrázků. Tento přístup není správný. Správný atribut pro kontextovou nápovědu je <tt>title</tt> [česky titulek]. Atribut <tt>alt</tt> [ze slova alternativní] má obsahovat alternativní popis obrázku pro prohlížeče, které neumějí zobrazovat obrázky, jako jsou různé textové prohlížeče, či hlasové syntetizátory pro nevidomé. To, že prohlížeč Internet Explorer tento alternativní popis zobrazuje jako nápovědu, není jeho výhodou, ale chybou způsobenou základním nepochopením atributů jazyka HTML programátory fy. Microsoft, která se díky rozšířenosti prohlížeče Internet Explorer ujala i mezi autory webových stránek. Více informací se dozvíte v komentářích u <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=25537">chyby 25537.</a></p><p>Pokud však bez této chyby nemůžete žít, tj často navštěvujete nevhodně napsané webové stránky, nainstalujte si rozšíření Popup ALT Attribute, které umožňovat zobrazit <tt>alt</tt> jako kontextovou nápovědu.</p>');

$faq->addQuestion('Poštovní odkazy nepracují z prohlížečem Mozilla Firefox?','<p>Jestliže používáte poštovního klienta z balíku Mozilla, už jste si pravděpodobně všimli, že při klepnutí na poštovní odkaz, prohlížeč Mozilla Firefox buďto neprovede nic nebo nastartuje Outlook Express. Toto chování je způsobeno nevhodným nastavením ovladače pro protokol mailto - tj tento ovladač je nastaven na Outlook Express nebo není nastaven vůbec. Pro ruční konfiguraci postupujte dle následujících kroků.</p><ol><li>Ve Windows 2k/XP, vyberte Možnosti složky v Ovládacích panelech, potom klepněte na panel Typy souborů.</li><li>Zde nalezněte (případně vytvořte) položku s příponou <q>(None)</q> a typem souboru <q>URL:MailTo Protocol</q> a klepněte na tlačítko na tlačítko Upřesnit.</li><li>Vyberte akci <q>open</q> a klepněte na tlačítko <span class="button">Upravit</span>.</li><li>Odeberte Použít DDE, vložte celou cestu k mozilla.exe uzavřenou do uvozovek a připojte <tt>-mail %1</tt>. Výsledek by měl vypadat, něco asi takto:<br/><code>"C:\Program Files\mozilla.org\Mozilla\mozilla.exe" -mail %1</code>.</li></ol>');

$faq->addQuestion('Proč mi prohlížeč Mozilla Firefox otevře nové okno, klepnu-li na URL odkaz v jiné aplikaci?','<p>Protože toto je standardní chování většiny aplikací. Pokud chcete toto chování změnit, a otvírat odkaz v aktuálním okně nebo v novém panelu, postupujte podle návodu uvedeného v dokumentu <a href="tipy-a-triky.html#tips:f5400c12c19b61c1ea45d56ad2aa5e79">Tipy &amp; triky.</a></p>');

$faq->show();
?>

<?php
	$page->includeFooter();
?>
